#### Numpy

In [2]:
!pip install numpy

In [7]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
arr2 = np.array([[1,2,3,4,5]])
print(arr2)
arr2.shape

[[1 2 3 4 5]]


(1, 5)

In [11]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
arr2.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [15]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
arr = np.array([[1,2,3],[3,4,5]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[[1 2 3]
 [3 4 5]]
(2, 3)
2
6
int64
8


In [4]:
import numpy as np

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("Add:",arr1 + arr2)

print("sub:",arr1-arr2)
print("Mul:",arr1*arr2)
print("Div:",arr1 /arr2)

Add: [11 22 33 44 55]
sub: [ -9 -18 -27 -36 -45]
Mul: [ 10  40  90 160 250]
Div: [0.1 0.1 0.1 0.1 0.1]


In [6]:
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [12]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("Array:\n",arr)
print(arr[1:,1:3])

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 7  8]
 [12 13]]


In [15]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[ 3  4  5]
 [ 8  9 10]]


In [17]:
print(arr[1:,2:])

[[ 8  9 10]
 [13 14 15]]


In [18]:
arr[0,0]=100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [19]:
arr[1:]=100
print(arr)

[[100   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [21]:
data = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
data[(data > 5) & (data <=8)]

array([6, 7, 8])

#### Mean,Median,Standard Deviation,Variance,Normalization


In [31]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(data)
print(f"Mean : {mean}")

median = np.median(data)
print(f"Median: {median}")

std_dev = np.std(data)
print(f"Standard Deviation: {std_dev}")

variance = np.var(data)
print(f"Variance: {variance}")

normalization_data = (data-mean) / std_dev
print(f"Normalization_data: {normalization_data}")

Mean : 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25
Normalization_data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]
